apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "isaac-app.fullname" . }}
  labels:
    {{- include "isaac-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "isaac-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "isaac-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "isaac-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SEGUE_CONFIG_LOCATION
              value: /local/data/conf/segue-config.properties
            - name: JAVA_OPTIONS
              value: -Dsegue.version={{ .Values.config.apiVersion}}
{{/*reenable*/}}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: isaac-config
            mountPath: /local/data/conf
          - name: git-content
            mountPath: /local/data/git-contentstore
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
            - clone
            - -c core.sshCommand=ssh -i /local/data/ssh-key/repo-private-key-rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -F /dev/null
            - {{ .Values.config.contentRepo }}
            - /local/data/git-contentstore
          volumeMounts:
            - name: isaac-ssh-key
              mountPath: /local/data/ssh-key
            - name: git-content
              mountPath: /local/data/git-contentstore
      volumes:
      - name: isaac-config
        secret:
          secretName: {{ .Values.config.secretName }}
      - name: isaac-ssh-key
        secret:
          defaultMode: 256
          secretName: {{ .Values.config.sshSecretName }}
      - name: git-content
        emptyDir: {}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
