apiVersion: v1
kind: Service
metadata:
  name: {{ include "isaac-app.chemChecker.fullname" . }}
  labels:
    {{- include "isaac-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chemChecker.service.type }}
  ports:
    - port: {{ .Values.chemChecker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "isaac-app.chemChecker.selectorLabels" . | nindent 4 }}