# Default values for isaac-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

isaac-app-fe:
  image:
    registry: ghcr.io
    repository: pelotech/isaac-react-app-cs
    tag: latest
  service:
    type: ClusterIP
  containerPorts:
    http: 80
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/load-balancer-name: shared-alb
      alb.ingress.kubernetes.io/group.name: shared-group
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: 'ip'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    hostname: www.isaac.classis.io
    path: "/*"
isaac-app-renderer:
  image:
    registry: ghcr.io
    repository: pelotech/isaac-react-app-cs-renderer
    tag: latest
  service:
    type: ClusterIP
  containerPorts:
    http: 80
elastic-search:
  protocol: http
  createCert: false
  imageTag: 8.5.3
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
  clusterName: isaac
  persistence:
    enabled: false
  replicas: 1
  secret:
    password: "testing123"
  resources: # bad needs fixed but temp on current hardware
    requests:
      cpu: "100m"
      memory: "300Mi"
    limits:
      cpu: "2000m"
      memory: "1Gi"

api:
  name: "api"
  replicaCount: 1

  image:
    repository: ghcr.io/pelotech/isaac-api
    tag: latest
    pullPolicy: Always

  imagePullSecrets: []

  config:
    apiVersion: v3.3.2-snapshot
    secretName: isaac-secrets
    sshSecretName: isaac-ssh-key
    contentRepo: git@github.com:pelotech/rutherford-content.git

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: enabled
    className: "alb"
    annotations:
      alb.ingress.kubernetes.io/load-balancer-name: shared-alb
      alb.ingress.kubernetes.io/group.name: shared-group
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: 'ip'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    hosts:
      - host: www.isaac.classis.io
        paths:
          - path: /isaac-api/*
            pathType: ImplementationSpecific
          - path: /api/*
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

etl:
  name: "etl"
  replicaCount: 1

  image:
    repository: ghcr.io/pelotech/isaac-api-etl
    tag: latest
    pullPolicy: Always

  imagePullSecrets: []

  config:
    apiVersion: v3.3.2-snapshot
    secretName: isaac-secrets
    sshSecretName: isaac-ssh-key
    contentRepo: git@github.com:pelotech/rutherford-content.git
    # JAVA_OPTIONS=-Dlog.path=/isaac-logs -Dsegue.version=$API_VERSION -Djetty.port=8090

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
